### ISSUE TITLE
Team Code Review Session

### ISSUE THREAD

**Issue by Danie12345** [jr-cast/Portfolio#4]
You can use 2 or more background images for the "about me" section, this would help you not to mess with the content flow and have hard times later on if you want to change something with the content flow, for example: doing the desktop version.

To remove any unwanted padding to the "My Recent Works" text, you should wrap everything in a flexbox at `body` level, and have the `flex-direction` set to `column`.

The background image at the headline section moves to the right when you make the viewport wider, you should have it either grow with the screen or centered with a fixed size.

**Comment by jr-cast** [comment]
Thanks for the feedback, I fixed the extra padding issue by removing the section semantic tag and placing a common div, I also updated the footer tags that was wrongly placed.
